### ISSUE TITLE
Debugger of 1.0.2 breaks SVG which uses fixed positioning

### ISSUE THREAD

**Issue by malaire** [elm/browser#92]
After updating `elm/browser` from version 1.0.1 to 1.0.2 the following app is broken when using `--debug` and while debugger window is NOT opened. While debugger window is opened app works correctly.

While broken the SVG is garbled (see images below) and program is nearly frozen.

Ellie: https://ellie-app.com/77w3QFJC7HDa1

Browser: Firefox 68.2.0esr
OS: Debian 10 "Buster"

With `elm/browser` 1.0.1:

![before](https://user-images.githubusercontent.com/6322120/68229119-4cb22f00-ffff-11e9-8256-0d7ff7bbaf99.png)

With `elm/browser` 1.0.2:

![after](https://user-images.githubusercontent.com/6322120/68229137-58055a80-ffff-11e9-9a8c-c89d86217240.png)

**Comment by malaire** [comment]
I simplified this example a bit too much. Originally it also had e.g. message triggered with mouse movement, which was not getting triggered while SVG was garbled, showing that program is frozen. (Original code where I noticed the problem is my [svg-drag-2 example](https://github.com/malaire/elm-examples/tree/master/svg-drag-2).)

**Comment by Skinney** [comment]
This is not a bug in the debugger.

You're applying css to _every_ svg on the page, telling the svg to fill the screen. Since the debugger button now is a svg, it fills the screen on top of the svg you're trying to display. Changing the css in your example to target the svg by id makes it work:

ellie: https://ellie-app.com/77yTDWDcqzQa1
